apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
 name: eorguessr-prod-issuer
 namespace: eorguessr-prod
spec:
 acme:
   email: john.dufaye@gmail.com
   server: https://acme-v02.api.letsencrypt.org/directory
  #  server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: eorguessr-prod-issuer-account-key
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik
